Repository Sparta-bootcamp-master-2team/NABAMovie, pull requests merged in 2025-04, with the labels that each got.

#5 Feat/#3
  .gitignore
  NABAMovie/NABAMovie.xcodeproj/project.pbxproj
  NABAMovie/NABAMovie/Data/Network/DTO/MovieDetailDTO.swift
  NABAMovie/NABAMovie/Data/Network/DTO/MovieImageDTO.swift
  NABAMovie/NABAMovie/Data/Network/DTO/NowPlayingMovieDTO.swift
  NABAMovie/NABAMovie/Data/Network/DTO/SearchMovieDTO.swift
  NABAMovie/NABAMovie/Data/Network/DTO/UpComingMovieDTO.swift
  NABAMovie/NABAMovie/Data/Network/MovieNetworkManager.swift
  NABAMovie/NABAMovie/Data/Repositories/MovieRepositoryImpl.swift
  NABAMovie/NABAMovie/Domain/Entity/MovieEntity.swift
  NABAMovie/NABAMovie/Domain/Entity/MovieStillsEntity.swift
  NABAMovie/NABAMovie/Domain/Protocol/MovieRepository.swift
  NABAMovie/NABAMovie/Domain/UseCase/FetchHomeScreenMoviesUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCase/FetchMovieStillsUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCase/FetchSearchMoviesUseCase.swift
  NABAMovie/NABAMovie/Resources/Info.plist
  NABAMovie/NABAMovie/Utils/Constants.swift
Labels: ✨Feature

#8 Feat/#7
  NABAMovie/NABAMovie/Data/DTO/UserDTO.swift
  NABAMovie/NABAMovie/Data/Repositories/AuthRepository.swift
  NABAMovie/NABAMovie/Data/Repositories/FavoriteMovieRepository.swift
  NABAMovie/NABAMovie/Data/Repositories/ReservationRepository.swift
  NABAMovie/NABAMovie/Data/RepositoryImpl/FirebaseAuthRepositoryImpl.swift
  NABAMovie/NABAMovie/Data/Service/FirebaseService.swift
  NABAMovie/NABAMovie/Data/Service/Protocol/FirebaseServiceProtocol.swift
  NABAMovie/NABAMovie/Domain/Entities/FavoriteMovie.swift
  NABAMovie/NABAMovie/Domain/Entities/Reservation.swift
  NABAMovie/NABAMovie/Domain/Entities/User.swift
  NABAMovie/NABAMovie/Domain/UseCases/AddFavoriteMovieUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/FetchFavoriteMoviesUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/FetchReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/LoginUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/LogoutUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/MakeReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/RegisterUseCase.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginView.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: ✨Feature

#9 Feat/#1
  NABAMovie/NABAMovie/Data/DTO/UserDTO.swift
  NABAMovie/NABAMovie/Data/Repositories/AuthRepository.swift
  NABAMovie/NABAMovie/Data/Repositories/FavoriteMovieRepository.swift
  NABAMovie/NABAMovie/Data/Repositories/ReservationRepository.swift
  NABAMovie/NABAMovie/Data/RepositoryImpl/FirebaseAuthRepositoryImpl.swift
  NABAMovie/NABAMovie/Data/Service/FirebaseService.swift
  NABAMovie/NABAMovie/Data/Service/Protocol/FirebaseServiceProtocol.swift
  NABAMovie/NABAMovie/Domain/Entities/FavoriteMovie.swift
  NABAMovie/NABAMovie/Domain/Entities/Reservation.swift
  NABAMovie/NABAMovie/Domain/Entities/User.swift
  NABAMovie/NABAMovie/Domain/UseCases/AddFavoriteMovieUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/FetchFavoriteMoviesUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/FetchReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/LoginUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/LogoutUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/MakeReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/RegisterUseCase.swift
  NABAMovie/NABAMovie/Extensions/UITextField/UITextField+.swift
  NABAMovie/NABAMovie/Extensions/UIView/UIView+.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginView.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: ✨Feature

#10 Feat/#2
  NABAMovie/NABAMovie/Presentation/MyPageView/MockData.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyInformationView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionHeaderView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageView.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/calendar 1.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/calendar 2.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/calendar.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/userImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/userImage.imageset/userImage.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/userImage.imageset/userImage2.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/userImage.imageset/userImage3.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/video 1.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/video 2.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/video.png
Labels: ✨Feature

#14 Bug/#13
  NABAMovie/NABAMovie/Data/Network/DTO/MovieDetailDTO.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MockData.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageView.swift
Labels: 🐛BugFix

#15 Feat/#4
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController+CollectionView.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/StillCutCell.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/mockPoster.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/mockPoster.imageset/mockPoster.jpeg
Labels: ✨Feature

#18 Feat/#11
  NABAMovie/NABAMovie/Data/Network/DTO/MovieDetailDTO.swift
  NABAMovie/NABAMovie/Domain/Entity/MovieEntity.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieItemCollectionView.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieItemCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieSearchViewController.swift
  NABAMovie/NABAMovie/Presentation/SearchView/ViewModel/MovieSearchViewModel.swift
Labels: ✨Feature

#20 Feat/#16
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewController.swift
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/screenImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/screenImage.imageset/screen.png
Labels: ✨Feature

#19 Feat/#6
  NABAMovie/NABAMovie/Data/Network/DTO/MovieDetailDTO.swift
  NABAMovie/NABAMovie/Domain/Entity/Movie/MovieEntity.swift
  NABAMovie/NABAMovie/Domain/Entity/Movie/MovieStillsEntity.swift
  NABAMovie/NABAMovie/Presentation/Components/HeaderView.swift
  NABAMovie/NABAMovie/Presentation/HomeView/CollectionView/HomeCollectionViewHeaderView.swift
  NABAMovie/NABAMovie/Presentation/HomeView/CollectionView/NowPlayingCell.swift
  NABAMovie/NABAMovie/Presentation/HomeView/CollectionView/NowPlayingFooterView.swift
  NABAMovie/NABAMovie/Presentation/HomeView/CollectionView/UpComingCell.swift
  NABAMovie/NABAMovie/Presentation/HomeView/HomeViewController.swift
  NABAMovie/NABAMovie/Presentation/HomeView/HomeViewModel.swift
  NABAMovie/NABAMovie/Presentation/MainView/MainViewController.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NABAMOVIE_LOGO(White).imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NABAMOVIE_LOGO(White).imageset/NABAMOVIE_LOGO(White) 1.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NABAMOVIE_LOGO(White).imageset/NABAMOVIE_LOGO(White)@2x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NABAMOVIE_LOGO(White).imageset/NABAMOVIE_LOGO(White)@3x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NBC_Logo.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NBC_Logo.imageset/NBC_Logo.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NBC_Logo.imageset/NBC_Logo@2x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/NBC_Logo.imageset/NBC_Logo@3x.png
  NABAMovie/NABAMovie/Utils/Extensions/UIViewController+Extensions.swift
Labels: ✨Feature

#21 Feat/#8
  NABAMovie/NABAMovie/Data/DTO/FavoriteMovieDTO.swift
  NABAMovie/NABAMovie/Data/DTO/ReservationDTO.swift
  NABAMovie/NABAMovie/Data/DTO/UserDTO.swift
  NABAMovie/NABAMovie/Data/Repositories/AuthRepository.swift
  NABAMovie/NABAMovie/Data/Repositories/FavoriteMovieRepository.swift
  NABAMovie/NABAMovie/Data/Repositories/ReservationRepository.swift
  NABAMovie/NABAMovie/Data/RepositoryImpl/FavoriteMovieRepositoryImpl.swift
  NABAMovie/NABAMovie/Data/RepositoryImpl/FirebaseAuthRepositoryImpl.swift
  NABAMovie/NABAMovie/Data/RepositoryImpl/ReservationRepositoryImpl.swift
  NABAMovie/NABAMovie/Data/Service/FirebaseService.swift
  NABAMovie/NABAMovie/Data/Service/Protocol/FirebaseServiceProtocol.swift
  NABAMovie/NABAMovie/Domain/Entities/FavoriteMovie.swift
  NABAMovie/NABAMovie/Domain/Entities/Reservation.swift
  NABAMovie/NABAMovie/Domain/UseCases/AddFavoriteMovieUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/CancelReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/FetchFavoriteMoviesUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/FetchReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/LoginUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/MakeReservationUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/RemoveAllFavoriteMoviesUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/RemoveFavoriteMovieUseCase.swift
  NABAMovie/NABAMovie/Extensions/UIViewController/UIViewController+.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: ✨Feature

#23 Feat/#12
  NABAMovie/NABAMovie/Data/Network/DTO/MovieDetailDTO.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ReservationDetailView.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ReservationDetailViewController.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ViewModel/ReservationDetailViewModel.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/qrcode.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/qrcode.imageset/qrcode1x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/qrcode.imageset/qrcode2x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/qrcode.imageset/qrcode3x.png
  NABAMovie/NABAMovie/Utils/Extensions/UIViewController+Extensions.swift
Labels: ✨Feature, ♻️Refactor

#26 Feat/#17
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewController.swift
  NABAMovie/NABAMovie/Presentation/Components/Divider.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/StillCutCell.swift
Labels: 👍Enhance, ♻️Refactor
