Repository Sparta-bootcamp-master-2team/NABAMovie, pull requests merged in 2025-05, with the labels that each got.

#28 Feat/#27
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewModel.swift
Labels: ✨Feature

#30 Feat/#24
  NABAMovie/NABAMovie/Domain/Entities/Movie/MovieEntity.swift
  NABAMovie/NABAMovie/Domain/Entities/Protocol/CellConfigurable.swift
  NABAMovie/NABAMovie/Domain/Entities/User/Reservation.swift
  NABAMovie/NABAMovie/Domain/UseCases/LogoutUseCase.swift
  NABAMovie/NABAMovie/Presentation/MovieListView/MovieListViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieListView/ViewModel/MovieListViewModel.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MockData.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyInformationView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/ViewModel/MyPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieItemCollectionView.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieItemCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieSearchViewController.swift
Labels: 👍Enhance, ✨Feature, ♻️Refactor

#33 Feat/#25
  NABAMovie/NABAMovie/App/Coordinator/AppCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/HomeCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/LoginCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/MyPageCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/Protocol/Coordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/SearchCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/TabBarCoordinator.swift
  NABAMovie/NABAMovie/App/DIContainer/AppDIContainer.swift
  NABAMovie/NABAMovie/App/DIContainer/HomeDIContainer.swift
  NABAMovie/NABAMovie/App/DIContainer/MyPageDIContainer.swift
  NABAMovie/NABAMovie/App/DIContainer/SearchDIContainer.swift
  NABAMovie/NABAMovie/App/DIContainer/TabBarDIContainer.swift
  NABAMovie/NABAMovie/App/SceneDelegate.swift
  NABAMovie/NABAMovie/Domain/UseCases/LogoutUseCase.swift
  NABAMovie/NABAMovie/Domain/UseCases/RegisterUseCase.swift
  NABAMovie/NABAMovie/Presentation/HomeView/HomeViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewModel.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.fill.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.fill.imageset/magnifyingglass.fill.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.fill.imageset/magnifyingglass.fill@2x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.fill.imageset/magnifyingglass.fill@3x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass@2x.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/magnifyingglass.imageset/magnifyingglass@3x.png
Labels: ✨Feature

#34 Feat/#22
  NABAMovie/NABAMovie/Data/RepositoryImpl/FirebaseUserRepositoryImpl.swift
  NABAMovie/NABAMovie/Data/Service/FirebaseService.swift
  NABAMovie/NABAMovie/Data/Service/Protocol/FirebaseServiceProtocol.swift
  NABAMovie/NABAMovie/Domain/Protocol/UserRepository.swift
  NABAMovie/NABAMovie/Domain/UseCases/RegisterUseCase.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/SignupView.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/SignupViewController.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/TermsAgreementView.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/TermsText.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/ViewModel/SignupViewModel.swift
  NABAMovie/NABAMovie/Utils/Extensions/UIViewController+Extensions.swift
Labels: ✨Feature

#35 feat: 마이페이지, 영화 검색 코디네이터 패턴 적용
  NABAMovie/NABAMovie/App/Coordinator/MyPageCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/SearchCoordinator.swift
  NABAMovie/NABAMovie/App/DIContainer/MyPageDIContainer.swift
  NABAMovie/NABAMovie/Presentation/CompletedSignUpView/CompletedSignUpViewController.swift
  NABAMovie/NABAMovie/Presentation/HomeView/HomeViewController.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieListView/MovieListViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieSearchViewController.swift
  NABAMovie/NABAMovie/Utils/Extensions/UIViewController+Extensions.swift
Labels: ✨Feature

#36 Feat/#29
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewController.swift
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
Labels: ✨Feature, ♻️Refactor

#38 Feat/#37
  NABAMovie/NABAMovie/App/Coordinator/AppCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/LoginCoordinator.swift
  NABAMovie/NABAMovie/App/DIContainer/AppDIContainer.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginView.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/SignupViewController.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/ViewModel/SignupViewModel.swift
Labels: ✨Feature

#42 Feat/#41
  NABAMovie/NABAMovie/Presentation/MyPageView/MyInformationView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/ViewModel/MyPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ReservationDetailView.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieSearchViewController.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/clock 1.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/clock 2.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/clock.png
  NABAMovie/NABAMovie/Utils/Extensions/UISearchBar+Extensions.swift
Labels: 👍Enhance, ✨Feature, ♻️Refactor

#45 Feat/#44
  NABAMovie/NABAMovie/App/Coordinator/AppCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/HomeCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/LoginCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/MovieInfoCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/MyPageCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/SearchCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/TabBarCoordinator.swift
  NABAMovie/NABAMovie/App/DIContainer/HomeDIContainer.swift
  NABAMovie/NABAMovie/App/DIContainer/TabBarDIContainer.swift
  NABAMovie/NABAMovie/App/Factory/AppFactory.swift
  NABAMovie/NABAMovie/App/Factory/HomeFactory.swift
  NABAMovie/NABAMovie/App/Factory/MovieInfoFactory.swift
  NABAMovie/NABAMovie/App/Factory/MyPageFactory.swift
  NABAMovie/NABAMovie/App/Factory/SearchFactory.swift
  NABAMovie/NABAMovie/App/Factory/TabBarFactory.swift
  NABAMovie/NABAMovie/App/SceneDelegate.swift
  NABAMovie/NABAMovie/Presentation/CompletedSignUpView/CompletedSignUpViewController.swift
  NABAMovie/NABAMovie/Presentation/HomeView/HomeViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieListView/MovieListViewController.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieSearchViewController.swift
Labels: ✨Feature

#43 Feat/#40
  NABAMovie/NABAMovie/Presentation/Login/LoginView.swift
  NABAMovie/NABAMovie/Presentation/Login/LoginViewController.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/SignupView.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/View/SignupViewController.swift
  NABAMovie/NABAMovie/Presentation/Signup/Signup/ViewModel/SignupViewModel.swift
Labels: 🐛BugFix, 👍Enhance, ♻️Refactor

#46 Feat/#39
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewController.swift
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/StillCutCell.swift
Labels: 👍Enhance, ✨Feature

#52 Feat/#50
  NABAMovie/NABAMovie/Presentation/MovieListView/MovieListViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyInformationView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionHeaderView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionView.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewController.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ReservationDetailView.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ReservationDetailViewController.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieItemCollectionView.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieItemCollectionViewCell.swift
  NABAMovie/NABAMovie/Presentation/SearchView/MovieSearchViewController.swift
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/calendar 3.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/calendar 4.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/calendarImage.imageset/calendar 5.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/clock 3.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/clock 4.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/clockImage.imageset/clock 5.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/Contents.json
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/video 3.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/video 4.png
  NABAMovie/NABAMovie/Resources/Assets.xcassets/videoImage.imageset/video 5.png
Labels: 👍Enhance, ♻️Refactor

#53 Feat/#47
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewController.swift
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
Labels: 👍Enhance, ✨Feature

#54 Feat/#51
  NABAMovie/NABAMovie/App/Coordinator/AppCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/HomeCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/LoginCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/MovieInfoCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/MyPageCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/SearchCoordinator.swift
  NABAMovie/NABAMovie/App/Coordinator/TabBarCoordinator.swift
  NABAMovie/NABAMovie/App/Factory/AppFactory.swift
  NABAMovie/NABAMovie/App/Factory/LoginFactory.swift
  NABAMovie/NABAMovie/App/Factory/MovieInfoFactory.swift
  NABAMovie/NABAMovie/App/Factory/MyPageFactory.swift
  NABAMovie/NABAMovie/App/SceneDelegate.swift
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewController.swift
  NABAMovie/NABAMovie/Presentation/BookingPage/BookingPageViewModel.swift
  NABAMovie/NABAMovie/Presentation/HomeView/CollectionView/UpComingCell.swift
  NABAMovie/NABAMovie/Presentation/HomeView/HomeViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieInfo/MovieInfoViewController.swift
  NABAMovie/NABAMovie/Presentation/MovieListView/MovieListViewController.swift
  NABAMovie/NABAMovie/Presentation/MyPageView/MyPageViewController.swift
  NABAMovie/NABAMovie/Presentation/ReservationDetailView/ReservationDetailViewController.swift
Labels: 🐛BugFix, ✨Feature
